// <auto-generated />
using System;
using HenabiAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HenabiAPI.Migrations
{
    [DbContext(typeof(HenabiDBContext))]
    partial class HenabiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("HenabiAPI.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HintId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("HenabiAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fuses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HenabiAPI.Models.GameCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameCards");
                });

            modelBuilder.Entity("HenabiAPI.Models.Hint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorHint")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GivingPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberHint")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReceivingPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeGiven")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GivingPlayerId");

                    b.HasIndex("ReceivingPlayerId");

                    b.ToTable("Hints");
                });

            modelBuilder.Entity("HenabiAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HenabiAPI.Models.Card", b =>
                {
                    b.HasOne("HenabiAPI.Models.Hint", null)
                        .WithMany("Cards")
                        .HasForeignKey("HintId");
                });

            modelBuilder.Entity("HenabiAPI.Models.GameCard", b =>
                {
                    b.HasOne("HenabiAPI.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.HasOne("HenabiAPI.Models.Game", "Game")
                        .WithMany("Cards")
                        .HasForeignKey("GameId");

                    b.HasOne("HenabiAPI.Models.Player", "Player")
                        .WithMany("CurrentHand")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Card");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HenabiAPI.Models.Hint", b =>
                {
                    b.HasOne("HenabiAPI.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("HenabiAPI.Models.Player", "GivingPlayer")
                        .WithMany()
                        .HasForeignKey("GivingPlayerId");

                    b.HasOne("HenabiAPI.Models.Player", "ReceivingPlayer")
                        .WithMany()
                        .HasForeignKey("ReceivingPlayerId");

                    b.Navigation("Game");

                    b.Navigation("GivingPlayer");

                    b.Navigation("ReceivingPlayer");
                });

            modelBuilder.Entity("HenabiAPI.Models.Player", b =>
                {
                    b.HasOne("HenabiAPI.Models.Game", null)
                        .WithMany("Players")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("HenabiAPI.Models.Game", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("HenabiAPI.Models.Hint", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("HenabiAPI.Models.Player", b =>
                {
                    b.Navigation("CurrentHand");
                });
#pragma warning restore 612, 618
        }
    }
}
